# Generated by Django 4.2.2 on 2024-01-31 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0002_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='pub_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
