# Generated by Django 4.2.2 on 2024-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0004_imgdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='jsonData',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
