# Generated by Django 4.2.2 on 2024-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0006_imgdetails_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDetails',
        ),
        migrations.AddField(
            model_name='imgdetails',
            name='projName',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='imgdetails',
            name='roomName',
            field=models.CharField(default='', max_length=120),
        ),
    ]
