# Generated by Django 4.2.2 on 2024-01-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0008_alter_imgdetails_negprompt_alter_imgdetails_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdetails',
            name='modelName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
