# Generated by Django 4.2.2 on 2024-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0009_imgdetails_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdetails',
            name='path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
