# Generated by Django 4.2.2 on 2024-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0010_alter_imgdetails_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdetails',
            name='objectsinit',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
