# Generated by Django 4.2.2 on 2024-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhome_app', '0011_imgdetails_objectsinit'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdetails',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
